channels:
- conda-forge
- defaults
dependencies:
- django=2.2
- djangorestframework=3.11.0
- black
- factory_boy
- flake8
- pip
- pytest-django
- pytest
- python-coreapi
- python=3.7
- requests
- sqlite
- sphinx
- pip:
  - conda-merge
  - django-appconf
  - django_extensions
  - safetydance_django
name: scoped_rbac
