channels:
- conda-forge
- defaults
dependencies:
- django=2.0.4
- djangorestframework=3.9.0
- factory_boy
- flake8
- pip=9.0.3
- pytest-django==3.4.4
- pytest==3.6
- python-coreapi
- python=3.6
- requests
- sqlite=3.25.3
- pip:
  - conda-merge
  - django-appconf==1.0.2
  - django_extensions
name: scoped_rbac
