# Generated by Django 2.0.4 on 2019-05-26 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('iri', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('definition_json', models.TextField()),
                ('rbac_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoped_rbac.Context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbac_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoped_rbac.Context')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoped_rbac.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='context',
            unique_together={('content_type', 'object_id')},
        ),
    ]
